### ISSUE TITLE
Create tree diagrams

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#12]
For all methods in the smallgraphs package which are used from other packages (= the implicit API)
1. find their callees recursively
2, create a diagram showing the tree of called methods

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/22

**Comment by TAKeanice** [comment]
Added [diagrams](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/tree/deprecations/metrics/Method%20call%20hierarchy)
