### ISSUE TITLE
Comment methods in the smallgraphs package according to their replaceability

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#14]
#12 provides several tree diagrams which show _when_ and _in which order_ methods in the smallgraphs package are called from outside.

Given such a tree, we seek to replace the methods which are nearest to the root node (the most "high level" methods) with methods from the jgrapht library.
Each team member is assigned a set of methods from the classes _teo.isgci.smallgraph.Graph_ and _teo.isgci.smallgraph.Configuration_ which they should comment using the conventions specified in the [Deprecations HOWTO](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/deprecations/teo/isgci/smallgraph/deprecations_HOWTO.md)

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/22
Assignees: @SPUNIKNSS15/morvdetfa

**Comment by TAKeanice** [comment]
@SPUNIKNSS15/graphinformation graphs of method usages can be found in the [Call Hierarchy](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/tree/deprecations/metrics/Method%20call%20hierarchy) folder. They should be really useful for evaluating the effect of changing, removing or replacing a method.

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by TAKeanice** [comment]
We already have replaced most methods on the fly.
