### ISSUE TITLE
Analyze how to avoid subgraph creation 

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#15]
According to the customer, the overall runtime could be drastically decreased by also applying VF2 on graphs with less than 100 nodes. 

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by TAKeanice** [comment]
At least he mentioned, that subgraph creation can be avoided due to VF2 being able to check subgraph isomorphism directly. We need to see where this can be applied.

**Comment by owdmn** [comment]
See https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/issues/18
