### ISSUE TITLE
Heap allocation overhead benchmarking

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#16]
Test how much the repeated graph creation/destruction on the heap influences the overall performance.

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
Any progress here? Is this even relevant anymore? @momits

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by crxxn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/issues/16

**Comment by momits** [comment]
This is no priority right now. If we find performance a major problem in the new implementation we can open a new issue (https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/tree/implementation_inheritance).
