### ISSUE TITLE
Implementing JGraphT graphs as a member variable of smallgraphs

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#17]
The easier way, might be much less of a hazzle compared to inherenting from JGraphT graphs.

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
Closed, as we follow the inheritance approach.

**Comment by momits** [comment]
We need to reopen this issue, because it was decided by the customer that this is a semantically more convincing approach than https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/issues/18.

**Comment by momits** [comment]
Retargeting this to our upcoming sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by TAKeanice** [comment]
Not completely finished yet. New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/26

**Comment by owdmn** [comment]
Configurations are now working on JGraphT objects instead of adjacency matrices and the current implementation passes all tests. 
I'm running FindISG once more to compare the new output.xml.

Changes here: https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/pull/24#event-330947782

**Comment by owdmn** [comment]
FindISG crashes as we're trying to reduce the transitive closure on a cyclic graph. Well...

**Comment by TAKeanice** [comment]
Fixed that by re-implementing copyFromComplement. Also meanwhile implemented getAutomorphisms() and isIsomorphic() in Configuration to use VF2 only
