### ISSUE TITLE
Implementing smallgraphs as a subclass of a JGraphT graph

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#18]
The nicer way, may be proven to be impossible in the given timeframe, even though this approach is far more elegant.

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by TAKeanice** [comment]
replaced every matrix usage in Graph.java with JGraphT Counterparts / removed unnecessary helper methods. Saved approx. 700 loc already.
See graphical representation in the [updated method call hierarchy diagram](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/implementation_inheritance/metrics/Method%20call%20hierarchy/CallHierarchy_afterInheritance.graphml). Relevant branch: [implementation_inheritance](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/tree/implementation_inheritance)

**Comment by TAKeanice** [comment]
And it is running forever... Cancelled first run forcefully.

**Comment by owdmn** [comment]
We've managed to get the FindISG process up and running in an acceptable time by avoiding the creation of all subgraphs of every graph, as the created USGs are thrown away anyway in the end.

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by momits** [comment]
In the last meeting the customer pointed out, that this is in fact _not_ the nicer way and we should follow the attribute approach. Main argument against inheritance is the fact, that configurations and families simply _are no graphs_, but sets of graphs with special properties.

=> Closing this for clarity.
