### ISSUE TITLE
Create profile of FindISG

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#27]

**Comment by momits** [comment]
new sprint https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/27

**Comment by TAKeanice** [comment]
@SPUNIKNSS15/graphinformation we could profile with/without JGraphT Optimization, with/without Complement optimization and all combinations of this to be able to present the individual improvements.

**Comment by TAKeanice** [comment]
Not necessary any more, since we have estimated times needed and the result of the runtime improvements silences every critical voice
