### ISSUE TITLE
Write unit tests for methods of teo.isgci.smallgraph package which use the adjacency matrix

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#6]
We want to replace the implementation of all methods which use the Graph.matrix attribute with their jgrapht counterpart. To achieve API compatibility and avoid regressions, we write the tests for the existing implementation first. In the next step #7 , we will replace the methods one by one and test the new implementation using the same tests.

**Comment by TAKeanice** [comment]
Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/21

**Comment by momits** [comment]
We put this issue on hold, for now, until we know how #14 is working out.

**Comment by TAKeanice** [comment]
New sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#22

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by owdmn** [comment]
This task is now tagged **urgent**  since we really need unittests by now!

**Comment by momits** [comment]
@crxxn can you please merge https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/pull/22 ?

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by momits** [comment]
**First observations:**

https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/implementation_inheritance/tests/data/observations/results_getGraphs_2015_09_06.md

**Comment by TAKeanice** [comment]
@momits What is "internal only"? Is it the results of getGraph() as executed in the unit test? And what does "in both" mean? Does that mean they have that number of common representatives?

**Comment by momits** [comment]
@TAKeanice I think you understood it correctly. We have two sets of representatives:
1. "From the sample" = all representatives of whom we know they are in the sample configuration
2. "Internal" = all representatives that are built by the current implementation

Then the columns mean:  
- "Sample only" = "From the sample"/"Internal"
- "Internal only" = "Internal"/"From the sample"
- "Both" = "From the sample" intersect "Internal"

As we found out this afternoon together with @285714 the error lies in the implementation of VF2. I will raise an issue for this.

**Comment by momits** [comment]
Opened issue https://github.com/SPUNIKNSS15/SPUNIKNSS15_jgrapht/issues/12 for the VF2 team.

**Comment by TAKeanice** [comment]
New Sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#26

**Comment by momits** [comment]
closing this.
we will track this in a more specific way:
https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/issues/26
