### ISSUE TITLE
Replace methods of teo.isgci.smallgraph.Graph which use adjacency matrices with their jgrapht counterparts

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#7]
Needs #6 to be finished.

**Comment by TAKeanice** [comment]
Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/21

**Comment by TAKeanice** [comment]
New sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#22
. On hold until we know the impact of exchanging JGraphT Methods for ISGCI Methods

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23
Still on hold, might be unnecessary at all depending on https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/issues/15

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by TAKeanice** [comment]
Methods are replaced, but the implementation now needs to be changed. Instead of letting Smallgraph inherit ListenableUndirectedGraph, we must use a member variable which we work with then, to be semantically correct (a smallgraph is _not_ a graph!)

**Comment by TAKeanice** [comment]
New Sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#26

**Comment by momits** [comment]
closing this as it does not represent what we are doing right now
