### ISSUE TITLE
Create "big" unittest

### ISSUE THREAD

**Issue by TAKeanice** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#8]
Create unit test that compares the whole program output given the input file [smallgraphs.xml](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/tests/data/smallgraphs.xml) with the sample output in [output.xml](https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/tests/tests/sample_output/output.xml)

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/21

**Comment by TAKeanice** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/22

**Comment by TAKeanice** [comment]
@crxxn any progress?

**Comment by owdmn** [comment]
We don't need this test anymore since our new VF2 produces a linewise identical output.xml compared to the external C++ VFlib. This issue may be reopened if replacing the internal isomorphy methods by VF2 dosen't yield the same result

**Comment by TAKeanice** [comment]
I'd say the latter is the case: When overhauling the process of finding subgraphs, there will be most probably changes to the line order.

**Comment by owdmn** [comment]
I've randomly compared _simple_ ISG elements of the old/original output.xml to the output of our current implementation and found all of the examined graphs to contain _exactly_ the same edge structure. My now-to-be-written haskell XML comparator will therefore rely on simple string comparison (instead of complex isomorphy tests) to compare the XMLs regarding graph objects.

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by owdmn** [comment]
The simple comparator is working but needs about 32Gb of ram - I've ran it on titan07 and found 682 simple graphs in both output.xml's, but only 577 matches. A match is a tuple of two graphs, where the node count and the edge xml-leaves are equal. - The 105 unmatched graphs may have differently ordered edge lists or are really not-isomorphic.

**Comment by TAKeanice** [comment]
Seems like the edge ordering is not the problem. Printing out smallgraphs is enough to manually check the difference, so the test is good enough.
